Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.product}-${self:custom.stage}-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          Required: true
          Mutable: true
        - Name: family_name
          Required: true
          Mutable: true
        - Name: email
          Required: true
          Mutable: true
        - Name: gender
          Required: true
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.product}-${self:custom.stage}-app
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  
  EditorsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Bliblou recipes editors
      GroupName: editors
      UserPoolId: !Ref CognitoUserPool
  
  ReviewersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Bliblou recipes reviewers
      GroupName: reviewers
      UserPoolId: !Ref CognitoUserPool
  
  PublishersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Bliblou recipes publishers
      GroupName: publishers
      UserPoolId: !Ref CognitoUserPool

Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
