Resources:
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: ${self:custom.product}-${self:custom.stage}-IdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName
 
Outputs:
  IdentityPoolId:
    Value: !Ref CognitoIdentityPool
    Export:
      Name: ${self:custom.product}-${self:custom.stage}-IdentityPoolId