Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.product}-${self:custom.stage}-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          Required: true
          Mutable: true
        - Name: family_name
          Required: true
          Mutable: true
        - Name: email
          Required: true
          Mutable: true
        - Name: gender
          Required: true
          Mutable: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT # DEVELOPER
        # From: Le Bliblou <securite@bliblou.com>
        ReplyToEmailAddress: aide-utilisateur@bliblou.com
        SourceArn: arn:aws:ses:eu-west-1:685910104720:identity/securite@bliblou.com
      VerificationMessageTemplate:
        EmailSubject: Votre code de vérification
        EmailMessage: <div dir="ltr"><div>Bonjour,</div><div><br></div><div>Votre code de vérification est <b>{####}</b>.</div><div><br></div><div>Merci de faire partie de la communauté du Bliblou !</div><div><br></div><div>Des questions ? Contactez-nous en répondant à ce message ou en nous écrivant à <a href="mailto:aide-utilisateur@bliblou.com">aide-utilisateur@bliblou.com</a></div><div><br></div><div>Cordialement,</div><div>Le Bliblou</div><div><a href="http://www.bliblou.com/">www.bliblou.com/</a><br></div><div><br></div><div><br></div><br clear="all"></div>

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.product}-${self:custom.stage}-app
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  
  ChefsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Bliblou recipes chefs
      GroupName: chefs
      UserPoolId: !Ref CognitoUserPool
  
  ReviewersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Bliblou recipes reviewers
      GroupName: reviewers
      UserPoolId: !Ref CognitoUserPool
  
  PublishersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      Description: Bliblou recipes publishers
      GroupName: publishers
      UserPoolId: !Ref CognitoUserPool

Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool

  UserPoolProviderName:
    Value: !GetAtt CognitoUserPool.ProviderName
    Export:
      Name: ${self:custom.product}-${self:custom.stage}-UserPoolProviderName

  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: ${self:custom.product}-${self:custom.stage}-UserPoolClient
